config/routes.rb
Rails.application.routes.draw do

 resources :clientes
 resources :professionals
 resources :servicios
 root to: "home#index"
 devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cliente.rb
class Cliente < ApplicationRecord
end

app/models/professional.rb
class Professional < ApplicationRecord
end

app/models/servicio.rb
class Servicio < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  before_action :set_cliente, only: [:show, :edit, :update, :destroy]

  # GET /clientes
  # GET /clientes.json
  def index
    @clientes = Cliente.all
  end

  # GET /clientes/1
  # GET /clientes/1.json
  def show
  end

  # GET /clientes/new
  def new
    @cliente = Cliente.new
  end

  # GET /clientes/1/edit
  def edit
  end

  # POST /clientes
  # POST /clientes.json
  def create
    @cliente = Cliente.new(cliente_params)

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to @cliente, notice: 'Cliente was successfully created.' }
        format.json { render :show, status: :created, location: @cliente }
      else
        format.html { render :new }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clientes/1
  # PATCH/PUT /clientes/1.json
  def update
    respond_to do |format|
      if @cliente.update(cliente_params)
        format.html { redirect_to @cliente, notice: 'Cliente was successfully updated.' }
        format.json { render :show, status: :ok, location: @cliente }
      else
        format.html { render :edit }
        format.json { render json: @cliente.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.json
  def destroy
    @cliente.destroy
    respond_to do |format|
      format.html { redirect_to clientes_url, notice: 'Cliente was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cliente
      @cliente = Cliente.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cliente_params
      params.require(:cliente).permit(:nombre, :direccion, :telefono, :servicio_requerido, :descripcion_del_servicio_requerido)
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index

  end

end

app/controllers/professionals_controller.rb
class ProfessionalsController < ApplicationController
  def index
     @professionals = Professional.all
  end

  def show
    @professional = Professional.find(params[:id])
  end

  def new
    @professional = Professional.new
  end

  def create
    @professional = Professional(professional_params)

    redirect_to professionals_path
  end

  def edit
    @professional = Professional.find(params[:id])
  end

  def update
    @professional = Professional.find(params[:id])
    @professional.update(professional_params)

    redirect_to professional_path(professional)
  end

  def destroy
    @professional = Professional.find(params[:id])
    @professional.destroy
  end

    redirect_to professionals_path

  private

  def professional_params
    params.require(:professional).permit(:nombre, :telefono, :profesion_u_oficio, :servicios_ofrecidos)
  end

  def current_professional
    @professional = Professional.find(params[:id])
  end
end

app/controllers/servicios_controller.rb
class ServiciosController < ApplicationController
  def index
    @servicios = Servicio.all
  end

  def show
    @servicio = Servicio.find(params[:id])
  end

  def new
    @servicio = Servicio.new
  end

  def created
    servicio = Servicio.create(dog_params)

    redirect_to servicios_path
  end

  def edit
    @servicio = Servicio.find(params[:id])
  end

  def update
    @servicio = Servicio.find(params[:id])

    @servicio.update(dog_params)

    redirect_to servicio_path(@servicio)
  end

  def destroy
    @servicio = Servicio.find(params[:id])

    @servicio.destroy

    redirect_to servicios_path
  end

  private

  def servicio_params
    params.require(:servicio).permit(:profesional, :descripcion)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/professionals_helper.rb
module ProfessionalsHelper
end

app/helpers/servicios_helper.rb
module ServiciosHelper
end

app/views/clientes/_form.html.erb
<%= form_with(model: cliente, local: true) do |form| %>
  <% if cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
        <% cliente.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nombre %>
    <%= form.text_field :nombre %>
  </div>

  <div class="field">
    <%= form.label :direccion %>
    <%= form.text_field :direccion %>
  </div>

  <div class="field">
    <%= form.label :telefono %>
    <%= form.number_field :telefono %>
  </div>

  <div class="field">
    <%= form.label :servicio_requerido %>
    <%= form.text_field :servicio_requerido %>
  </div>

  <div class="field">
    <%= form.label :descripcion_del_servicio_requerido %>
    <%= form.text_area :descripcion_del_servicio_requerido %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clientes</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Direccion</th>
      <th>Telefono</th>
      <th>Servicio requerido</th>
      <th>Descripcion del servicio requerido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clientes.each do |cliente| %>
      <tr>
        <td><%= cliente.nombre %></td>
        <td><%= cliente.direccion %></td>
        <td><%= cliente.telefono %></td>
        <td><%= cliente.servicio_requerido %></td>
        <td><%= cliente.descripcion_del_servicio_requerido %></td>
        <td><%= link_to 'Show', cliente %></td>
        <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
        <td><%= link_to 'Destroy', cliente, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New Cliente</h1>

<%= render 'form', cliente: @cliente %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @cliente.nombre %>
</p>

<p>
  <strong>Direccion:</strong>
  <%= @cliente.direccion %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @cliente.telefono %>
</p>

<p>
  <strong>Servicio requerido:</strong>
  <%= @cliente.servicio_requerido %>
</p>

<p>
  <strong>Descripcion del servicio requerido:</strong>
  <%= @cliente.descripcion_del_servicio_requerido %>
</p>

<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/home/index.html.erb
<div class="jumbotron text-center">
 <h2>¡Bienvenidos a Home!</h2>
 <% if user_signed_in? %>
 <% else %>
   <p>
     <%= link_to "Iniciar sesión", new_user_session_path, class: "btn btn-default btn-lg" %>
     <%= link_to "Regístrate", new_user_registration_path, class: "btn btn-primary btn-lg" %>
   </p>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ServiciosHogar</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

      <nav class="navbar navbar-expand-lg navbar-light navbar-color">
  <a class="navbar-brand" href="#">Navbar</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item active">
        <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#">Link</a>
      </li>
      <li class="nav-item">
        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>
    <div class="alert alert-info"><%= notice %></div>
    <div class="alert alert-warning"><%= alert %></div>

    <%= yield %>
  </body>
</html>

app/views/professionals/edit.html.erb
<h3>Update Professional Details</h3>
<%= form_with model: @professional do |form| %>
<%= form.text_field :nombre, placeholder: "nombre" %>
<%= form.text_field :telefono, placeholder: "telefono" %>
<%= form.text_field :profesion_u_oficio, placeholder: "profesion_u_oficio" %>
<%= form.text_field :servicios_ofrecidos, placeholder: "servicios_ofrecidos" %>

<%= form.submit %>
<% end %>

app/views/professionals/index.html.erb
<table>
  <% @professionals.each do |professional| %>
    <tr>
      <td><%= link_to professional.nombre, professional_path(professional) %></td>
      <td><%= button_to 'Edit', edit_professional_path(professional), method: 'get' %></td>
      <td><%= button_to 'remove', professional_path(professional), method: 'delete', data: {confirm: 'Are you sure?'} %></td>
  <% end %>
</table>
<%= link_to "Add a New Professional", new_professional_path %>

app/views/professionals/new.html.erb
<h3>crear Profesional</h3>
<%= form_with model: @professional do |form| %>
  <%= form.text_field :nombre, placeholder: "nombre" %>
  <%= form.text_field :telefono, placeholder: "telefono" %>
  <%= form.text_field :profesion_u_oficio, placeholder: "profesion_u_oficio" %>
  <%= form.text_field :servicios_ofrecidos, placeholder: "servicios_ofrecidos" %>

  <%= form.submit %>
<% end %>

app/views/professionals/show.html.erb
<h1><%= @professional.nombre %></h1>
<h4><%= @professional.telefono %></h4>
<h4><%= @professional.profesion_u_oficio %></h4>
<h4><%= @professional.servicios_ofrecidos %></h4>
<%= link_to 'Remove', @professional, method: :delete, data: {confirm: 'Are you sure' } %>

app/views/servicios/edit.html.erb
<h3>Actualizar Servicios</h3>

<%= form_with model: @servicio do |form| %>

  <%= form.text_field :profesional, placeholder: "profesional" %>

  <%= form.text_field :descripcion, placeholder: "descripcion" %>

  <%= form.submit %>

<% end %>

app/views/servicios/index.html.erb
<ul>
  <% @servicios.each do |servicio| %>

   <li><%= link_to servicio.profesional, servicio_path(servicio) %></li>

  <% end %>

</ul>

app/views/servicios/new.html.erb
<h3>Crear Servicio</h3>

<%= form_with model: @servicio do |form| %>

  <%= form.text_field :profesional, placeholder: "profesional" %>

  <%= form.text_field :descripcion, placeholder: "descripcion" %>

  <%= form.submit %>

<% end %>

app/views/servicios/show.html.erb
<h1><%= @servicio.profesional %></h1>

<h4><%= @servicio.descripcion %></h4>

<%= link_to "remove", @servicio, method: :delete, data: {confirm: 'Are yoy sure?'} %>